### ISSUE TITLE
Error: We don't support that file type!

### ISSUE THREAD

**Issue by WaGi-Coding** [Auo/ImgurSharp#3]
I try the memorystream example with png, jpg and mp4, but i always get the ResponseException: "Error: We don't support that file type!"

No clue what i am doing wrong ^^

**Comment by Auo** [comment]
I've not done any work on this project in quite some time, but I'll try to help.

Could you produce an example of how you're using the project? (Mainly just the method that uploads the image)
Are you certain that the file you're trying to upload is actually a valid png,jpeg?

**Comment by Auo** [comment]
Closing since no response
